encyclopedia/urls.py
from django.urls import path

from . import views

app_name="encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("random", views.random, name="random"),
    path("edit/<str:entry>", views.edit, name="edit"),
    path("<str:entry>", views.entry, name="entry"),
    
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseNotFound, Http404, HttpResponse
from markdown2 import Markdown
from . import util
from random import shuffle


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, entry):
	if util.get_entry(entry):
		return render(request, "encyclopedia/entry.html", {
			"article": Markdown().convert(util.get_entry(entry)),
			"title": entry
			})
	#return HttpResponseNotFound("<h1>Page not found</h1>")
	#raise Http404("Page not found")
	return render(request, "encyclopedia/error.html")

def search(request):
	q = request.POST.get("q")
	articles_list = util.list_entries()

	if util.get_entry(q):
		return redirect("encyclopedia:entry", entry=q)
	elif q in "".join(articles_list):
		return render(request, "encyclopedia/search_results.html", {
			"articles_list": articles_list,
			"q": q
			})
	else:
		return render(request, "encyclopedia/search_results.html", {
			"articles_list": [],
			"q": q
			})

def create(request):
	if request.method == "GET":
		return render(request, "encyclopedia/create.html")
	elif request.method == "POST":
		title = request.POST.get("content").split()[1]
		content = request.POST.get("content")
		if title in util.list_entries():
			return render(request, "encyclopedia/create_error.html")
		# Add .md file to 'entries' folder
		util.save_entry(title, content)
		return redirect("encyclopedia:entry", entry=title)

def edit(request, entry):
	content = util.get_entry(entry)
	if request.method == "GET":
		return render(request, "encyclopedia/edit.html", {
			"entry": entry,
			"content": content
			})
	elif request.method == "POST":
		new_content = request.POST.get("content")
		util.save_entry(entry, new_content)
		return redirect("encyclopedia:entry", entry=entry)

def random(request):
	entries = util.list_entries()
	shuffle(entries)
	entry = entries[0]
	return redirect("encyclopedia:entry", entry=entry)

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Create new page
{% endblock %}


{% block body %}
<form action="create" method="post">
	{% csrf_token %}
	<br>
	<h2 style="margin-left: 40px">Create New Page</h2>
	<hr>
	<textarea name="content" id="content" placeholder="Enter Markdown text" style="height: 600px; width: 60%; margin: 20px 45px; padding:5px; outline: none; box-shadow: 1px 1px 3px 2px rgba(0,0,0,0.1); border-color: gray"></textarea>
	<br>
	<button type="submit" style="position: relative; left: 785px; border-radius: 2px; padding: 1px 5px 1px; font-size: 18px">Create Page</button>
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/create_error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Page already exists
{% endblock %}


{% block body %}
<h3>Error:</h3>
Page you're trying to add already exists.
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Create new page
{% endblock %}


{% block body %}
<form action="{{entry}}" method="post">
	{% csrf_token %}
	<br>
	<h2 style="margin-left: 40px">Edit page</h2>
	<hr>
	<textarea name="content" id="content" placeholder="Enter Markdown text" style="height: 600px; width: 60%; margin: 20px 45px; padding:5px; outline: none; box-shadow: 1px 1px 3px 2px rgba(0,0,0,0.1); border-color: gray">{{ content }}</textarea>
	<br>
	<button type="submit" style="position: relative; left: 806px; border-radius: 2px; padding: 1px 5px 1px; font-size: 18px">Edit Page</button>
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
{{ article|safe }}
<hr>
<a href="{% url 'encyclopedia:edit' title %}">Edit page</a>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Not found
{% endblock %}

{% block body %}
<h2>Error: Page not found</h2>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <link rel="icon" href="https://img.icons8.com/all/500/wikipedia.png">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="search" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Search results
{% endblock %}

{% block body %}
<h1>Search results for "{{ q }}":</h1>
<ul>
{%  for article in articles_list %}
	{% if q in article %}
		<li><a href="{% url 'encyclopedia:entry' article %}">{{ article }}</a></li>

	{% endif %}
{% empty %}
	<li>Nothing matching "{{ q }}" was found</li>

{% endfor %}
</ul>
{% endblock %}